### ISSUE TITLE
Is there a way to add cards to subdecks?

### ISSUE THREAD

**Issue by aseals** [taylormitchell/ankify_roam#10]
Is there an existing method to direct a card to a specific subdeck within a deck?
<img width="279" alt="Screen Shot 2020-12-13 at 10 23 31 AM" src="https://user-images.githubusercontent.com/7329800/102016144-6ad37e00-3d2d-11eb-8d27-beb6184aaafb.png">

**Comment by taylormitchell** [comment]
Hey @aseals 

I'd never tried before but it turns out you can! You just need to give the deck and subdeck name separated by double colon. In your case, you could add something to the "Consonants, Vowels, & Sounds" deck with the following:

```
ankify_roam add my_roam_db.json --deck="Hebrew::Consonants, Vowels, & Sounds"
```
I hope that helps!

**Comment by aseals** [comment]
Thank you, that worked perfectly!

I tried replicating the same thing in-line on Roam similar to "2+2={4} #[[[[ankify]]:deck="Math::Addition"]]", however, it did not work quite as well. Adding subdecks in-line this way would be useful when automatically syncing Roam & Anki so all the cards go to the right place.

**Comment by taylormitchell** [comment]
Hey @aseals

I just pushed a change which should make this work. Can you try installing the latest version and see if it does?
```
pip install git+https://github.com/taylormitchell/ankify_roam.git
```

**Comment by aseals** [comment]
Hey @taylormitchell 

Apologies for the delay. I just tested this out and it works like a charm!

**Comment by taylormitchell** [comment]
Great!
