### ISSUE TITLE
[bug] continuous indentation data skipped in flashcard generation 

### ISSUE THREAD

**Issue by monk-blade** [taylormitchell/ankify_roam#18]
When there is two lines of continues indentation after main front card, it is not generating proper back card. 
Screenshots

[[BUG]]
Roamresearch note: 
![image](https://user-images.githubusercontent.com/1335766/118084376-3ba96180-b3de-11eb-8648-046e71203bbe.png)
 Ankidroid flashcard:
![image](https://user-images.githubusercontent.com/1335766/118084477-6bf10000-b3de-11eb-898f-97af86ce2824.png)

[[SOLVED]]
After removing indentation of second line of back card
Roamresearch note:
![image](https://user-images.githubusercontent.com/1335766/118085695-6dbbc300-b3e0-11eb-900b-e9573f13c665.png)
Ankidroid flashcard:
![image](https://user-images.githubusercontent.com/1335766/118085755-875d0a80-b3e0-11eb-94c2-2b78b1caaaf3.png)

**Comment by taylormitchell** [comment]
Hey @arpan-chavda. Thanks for all the info. I wasn't able to replicate this on my end using the latest version `v0.1.0`. Can you let me know what version you're using?
```
ankify_roam --version
```

**Comment by arpan-chavda** [comment]
![image](https://user-images.githubusercontent.com/1335766/118210712-78ca2e00-b488-11eb-983a-e8bb629f5a1c.png)
