### ISSUE TITLE
Logseq support

### ISSUE THREAD

**Issue by monk-blade** [taylormitchell/ankify_roam#23]
I know it is irrelevant to ask here. I think logseq is powerful alternative to roam research. it will be easy to support logseq as they have many export options.

**Comment by taylormitchell** [comment]
Agreed logseq seems neat. I don't use it myself though and wouldn't consider adding support it unless I start to. I'd say your best bet is to find someone who uses logseq and knows python and then ask them to fork this project and adapt. As you say, it shouldn't be too hard
