### ISSUE TITLE
Some quick user notes

### ISSUE THREAD

**Issue by Etyre** [taylormitchell/ankify_roam#40]
These are some minor user-feedback / feature requests. These are way lower priority than either [latex support](https://github.com/taylormitchell/ankify_roam/issues/33) or the [bug that I've been having](https://github.com/taylormitchell/ankify_roam/issues/38) with some of my cloze cards, but they seem worth noting anyway.

* **Tagging documentation**: It appears that any tags anywhere on the "workflowy-path" of a block tagged with #ankify are added as tags to the anki card as well. This is great! Tagging this way is easy enough that that I will actually use tags in anki. For one thing this means that I can add a number of tags at the top of a page, and all the blocks under them will inherit those tags, so I mostly don't have to think about it.  - All this is great, but it isn't documented in the readme, which maybe you want to do?
* **URLs don't show up as links**: When I make an anki card that includes a URL, manually, that URL automatically becomes a hyperlink to that URL. I can't figure out how to put links in cards via ankify_roam, at all. URLs aren't links by default, and using the standard markdown link format for roam (`[link](url)`) doesn't seem to help?
* **Adding line spaces?**: When I ankify a roam block that has a line space in it, the line space disappears in the card. Is there a way that I can add line spaces? 

Thanks!
Eli

**Comment by taylormitchell** [comment]
Thanks for the feedback! I created separate issues for each so I'm closing this one. No promises on timeline but I planning to do a sprint on ankify_roam in a couple weeks so I may be able to get to them then
