### ISSUE TITLE
URLs don't show up as links

### ISSUE THREAD

**Issue by taylormitchell** [taylormitchell/ankify_roam#41]
When I make an anki card that includes a URL, manually, that URL automatically becomes a hyperlink to that URL. I can't figure out how to put links in cards via ankify_roam, at all. URLs aren't links by default, and using the standard markdown link format for roam ([link](url)) doesn't seem to help?

From: https://github.com/taylormitchell/ankify_roam/issues/40

**Comment by Etyre** [comment]
Fixed for me.

Thank you!
