### ISSUE TITLE
Feature request: it would be great if I could suspend or unsuspend anki cards from roam, with tags

### ISSUE THREAD

**Issue by Etyre** [taylormitchell/ankify_roam#48]
My workflow entails sometimes suspending or un-suspending anki notes, depending on a number of factors.

It would be great if I could do this, in roam, with a tag something. 

I'm imagining something like the following, in roam...

```
- What is the capital of France? #ankify #suspend
   - Paris
```
...changes the relevant card's state to "suspended" in anki, but that when you remove the `#suspend` tag, that un-suspends it.

This is helpful because it would allow me to see, from roam, which cards I've suspended. Currently I might think that I need an anki card for some question, and see that there's already an existing one, not realizing that the associated card is suspended, and not in my reviews. And because of that, I can't be sure that a card isn't suspended, which means that I have to go and look it up in my anki database, defeats most of the point of this.

But if I could suspend and unsuspend notes with tags, I could do all this from roam, which I think would allow me to do 100% (with some edge case suggestions) of my anki management from Roam!

(I'm thinking about if there's a way that I could do this without any changes to ankify_roam. The best that I can come up with right now is writing a script that filters for all notes that have the `#ankify` tag **and** the `#suspend` tag, and suspends them, and then filters for all notes that have the `#ankify` tag, but **not** the `#suspend` tag, and un-suspend those. I'm not a software engineer, but I might spend a little bit of time tinkering with this.)

**Comment by taylormitchell** [comment]
@Etyre Added this feature in v0.1.4 #36. To suspend a note from Roam, add the `#[[ankify_roam: suspend=True]]` tag to it. Any card which inherits that tag will also be suspended. You can also insure a note *isn't* suspended by tagging it with `#[[ankify_roam: suspend=False]]`. See https://github.com/taylormitchell/ankify_roam/blob/master/CHANGELOG.md

**Comment by Etyre** [comment]
Hm. This doesn't work for me, with some weird side effects.

If I add the `#[[ankify_roam: suspend=True]]` tag to a block, that tag is not added to the note in anki, and the note is not suspended. However, it does add an extra tag to the anki note: the name of the page that the block is on!

For instance this roam snippet...

<img width="553" alt="Screen Shot 2022-04-13 at 11 54 04 AM" src="https://user-images.githubusercontent.com/23288300/163251534-373cd858-13c0-48e9-8cf2-3aea8bf1967d.png">

...produces this anki note.

<img width="851" alt="Screen Shot 2022-04-13 at 11 54 10 AM" src="https://user-images.githubusercontent.com/23288300/163251745-c760010a-b2e5-4cad-837c-a19b93e23d95.png">
As you can see, the tag `#quine` is not present on the roam side, but the `#[[ankify_roam: suspend=True]]` is missing on the anki side.


Same thing with this card.

<img width="530" alt="Screen Shot 2022-04-13 at 11 55 09 AM" src="https://user-images.githubusercontent.com/23288300/163252068-836e2084-1191-43e5-8253-627041f55b9b.png">

<img width="851" alt="Screen Shot 2022-04-13 at 11 54 51 AM" src="https://user-images.githubusercontent.com/23288300/163252088-a13ab522-82d3-4072-93a5-3bc7413ff261.png">

Any idea what's up with that?

**Comment by Etyre** [comment]
This is great! : ) 

Thank you!
