### ISSUE TITLE
Sometimes higher level nodes are not ideal for making QA cards

### ISSUE THREAD

**Issue by CoffeeDrinkRabbit** [taylormitchell/ankify_roam#5]
Regarding Basic cards, the nodes that currently have #ankify added will appear as the question part of the card, and their children will appear as the answer part of the card. In addition to that, the Children’s children will also appear as an answer on the back of the card.

When higher-level nodes are added with #ankify, you end up with the back of the card which is kind of a hard bone to chew on：
pic1: https://imgchr.com/i/wqRURH

I understand that there are situations where all the subnodes need to be remembered, but for information that needs to be remembered layer by layer, it would seem more appropriate to just have the lower level subnodes as the back of the card, for example ：
pic2：https://imgchr.com/i/wqRNJe

**Comment by taylormitchell** [comment]
Hmm, I hadn't considered this before but now that you mentioned it, some of my cards could benefit from this. I like the idea but I think having this as the default behaviour might be unintuitive for new users. 

What do you think of having this as an option that the user can control? Either at the command line `--max-depth=1`, which would apply to all cards, or on a per-card basis with a tag eg. #[[max-depth=1]]

**Comment by taylormitchell** [comment]
Good points! I agree there's value in both. Adding this to my list of next features to implement

Thanks for the suggestion 👍

**Comment by mblackwo** [comment]
Thanks for pointing this out, additional question, how can this work for cloze deletion questions?  As an **example:**

![2020-10-12_09-58-05](https://user-images.githubusercontent.com/69804771/95754851-9ffe1a00-0c71-11eb-9050-32076799e7b9.png)

**Comment by taylormitchell** [comment]
@mblackwo There's no way to do that at the moment. Cloze cards don't include the child blocks, they only include the block with the #ankify tag. I plan to add the ability to do this - maybe in the next release.

**Comment by taylormitchell** [comment]
Added `max-depth` with release 0.1.0 (#16) which addresses this issue
