### ISSUE TITLE
I can't get the automated import to work.

### ISSUE THREAD

**Issue by Etyre** [taylormitchell/ankify_roam#9]
The roam-to-git part seems to be working and backing up every hour, but I can't get the crontab command you recommend to work. (For one thing, it looks like it has an extra set of quotes: I don't think that the part that comes after the timing should be quoted.)

Does it work for you?

**Comment by taylormitchell** [comment]
Hey Etyre,

I have it working on my end but I have a slightly different set up than what is shown on the README. Try setting it up this way:

Open your terminal and run `crontab -e` to open up your cron jobs.

Add the following two lines to it. The first pulls the latest roam-to-git backup on github down to your local copy every hour. The second one runs ankify_roam 15 minutes after that. You'll need to replace the paths with your own: 
```
0 * * * * cd ~/GitHub/roam_backup;git fetch --all;git reset --hard origin/master
15 * * * * ankify_roam add ~/GitHub/roam_backup/json/my_roam.json
```
Hope that helps!
